//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocation
    {
        public int allocId { get; set; }
        public Nullable<int> projId { get; set; }
        public Nullable<int> resId { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<decimal> allocation1 { get; set; }
        public Nullable<bool> isBillable { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<int> technology { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual Technology Technology1 { get; set; }
        public virtual Role Role1 { get; set; }
    }
}
