//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int regId { get; set; }
        public string regName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string mobile { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string address { get; set; }
        public string gender { get; set; }
    }
}
