//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource()
        {
            this.Allocations = new HashSet<Allocation>();
            this.Projects = new HashSet<Project>();
        }
    
        public int resId { get; set; }
        public string resName { get; set; }
        public string resDepartment { get; set; }
        public Nullable<int> technologyGroup { get; set; }
        public Nullable<int> primaryTechnology { get; set; }
        public Nullable<int> secondaryTechnology { get; set; }
        public Nullable<int> designation { get; set; }
        public Nullable<int> resRole { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allocation> Allocations { get; set; }
        public virtual Designation Designation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        public virtual Technology Technology { get; set; }
        public virtual Role Role { get; set; }
        public virtual Technology Technology1 { get; set; }
        public virtual technologyGroup technologyGroup1 { get; set; }
    }
}
